package cpp.Absyn; // Java Package generated by the BNF Converter.

public class Marker {
  public  String expr_;
  
  public Marker(String expr_) { this.expr_ = expr_;}

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof cpp.Absyn.Marker) {
      cpp.Absyn.Marker x = (cpp.Absyn.Marker)o;
      return this.expr_.equals(x.expr_);
    }
    return false;
  }

}
