package cpp.Absyn; // Java Package generated by the BNF Converter.

public class Typearray extends Type {
  public  Type type_;
  public  int  level_=1;
  public  Type internal_;

  public Typearray(Type p1) {
    internal_ = type_ = p1;
    if (p1 instanceof Typearray) {
      Typearray t= (Typearray)p1;
      type_ = t.type_;
      level_ = t.level_+1;
    }
  }

  public <R,A> R accept(cpp.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof cpp.Absyn.Typearray) {
      cpp.Absyn.Typearray x = (cpp.Absyn.Typearray)o;
      return this.type_.equals(x.type_);
    }
    return false;
  }

  public int _hashCode() {
    return this.type_.hashCode();
  }


}
