#!/bin/sh
cd cpp/Absyn/
for i in *java
do 
	echo Editing $i
	cat $i | sed "s/final//" | sed "s/public int hashCode/public int _hashCode/"> $i.new
	mv $i.new $i
done
cd ../../
cp Typearray.java cpp/Absyn

echo Recompiling...
javac cpp/Absyn/*.java
